[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W"]  # Error, formatting, warnings
ignore = ["E501"]         # Ignore long lines if you want
exclude = ["venv", ".venv", "__pycache__"]
